index.html

Updating to use new URL for playbooks site

---

Jenkinsfile
build/dev/params
build/template.yml
deploy/dev/params
deploy/prod/params
deploy/template.yml

Added pipelines similar to the playbooks site.
@rdebeasi @JaredBurck @sabre1041

Pipeline completion

---

build/dev/params

Repointing pipeline

---

.dockerignore
.gitignore
CONTRIBUTING.md
Gemfile
container-images/README.adoc
container-images/hugo/Dockerfile
container-images/hugo/root/usr/bin/entrypoint

Adds a builder image for testing changes to the site.
See new usage instructions in:
- CONTRIBUTING.md
- container-image/hugo/README.adoc
resolve #13 
-----
-----

Adding builder image and documentation

---

README.md

See title
Read the README.md
n/a
-----
-----

Revising our intro statement and background

---

gulpfile.babel.js

Addresses issue #61 
Start live preview with `npm start`. Then make a change to the theme scss, save it, and make sure you can see the change when the browser reloads.
#61 
-----
-----

Fixing gulpfile so that live reload works on the theme stylesheets

---

site/content/articles/ldap-group-sync.adoc
site/content/articles/openshift-custom-certificates.adoc
site/content/articles/openshift-ldap-integration.adoc
site/content/guides/external-jenkins-integration.adoc
site/content/guides/openshift-admin-overview.adoc
site/content/guides/openshift-ha-installation.adoc
site/content/guides/openshift-load-balancing.adoc
site/content/guides/openshift-monitoring-guide.adoc
site/content/guides/openshift-pre-install.adoc
site/content/guides/openshift-validate.adoc

I modified the adoc files to include a more tag to the documents so the summary page could be shorter and not just the first 70 lines of the file
Spin up your local hugo and test my pr
https://github.com/redhat-cop/uncontained.io/issues/41
-----
-----

added summary breaks to all the adoc files using the more tag

---

site/themes/uncontained.io/layouts/_default/single.html
site/themes/uncontained.io/layouts/partials/author.html
site/themes/uncontained.io/src/scss/_content.scss
site/themes/uncontained.io/src/scss/_typography.scss
site/themes/uncontained.io/src/scss/_variables.scss

This PR implements most of the remaining guidance from our style guide, including:
- Content Headings
- Author and date styling
Build with
```
npm start
```
Examine article content.
n/a
-----
-----

Style guide typography

---

site/content/about/brand.adoc
site/themes/uncontained.io/layouts/partials/header.html
site/themes/uncontained.io/src/scss/_content.scss
site/themes/uncontained.io/src/scss/_typography.scss
site/themes/uncontained.io/src/scss/_variables.scss

Styling for code blocks
Build site
```
npm build
```
Navigate to site content and style guide and examine various use of code blocks.
#34 #33 
-----
-----

Add styling for code blocks

---

site/themes/uncontained.io/src/scss/_content.scss
site/themes/uncontained.io/src/scss/_variables.scss

Apply table styling for content.
```
npm install
npm start
```
Look at an article that contains tables (the OpenShift Monitoring Guide has several), and ensure it is readable.
#73 
-----
-----

Add styling for tables in content

---

.gitignore
.openshift/files/hugo-build.yml
package-lock.json
site/themes/uncontained.io/layouts/index.html
site/themes/uncontained.io/src/scss/_base.scss
site/themes/uncontained.io/src/scss/_footer-main.scss

Fixes styling of footer to force it to fill any empty space at the bottom of the page on large screens.
Also fixes the openshift buildConfig to build the main fork/master branch.
Build site:
```
npm install
npm start
```
Then look on the homepage at high resolution. You should see the blue footer bar fill the available horizontal space rather than "floating" above empty gray space.
n/a
-----
-----

Ensure footer fills empty space at the bottom of a page

---

site/themes/uncontained.io/layouts/_default/single.html

Brief explanation of the guide or document changes you have made and/or the new content you are contributing.
Include any information or commands (please use code blocks) to help reviewers understand and verify your contribution.
Provide a link to any open Github issues or Trello cards that describe the use case or problem you are solving.
Fixes issue #79 : Article content spilling over outside of page boundaries
-----
-----

updated css

---

package-lock.json
site/config.toml
site/themes/uncontained.io/README.md
site/themes/uncontained.io/layouts/partials/header.html

Add Google Analytics tag to theme; add ID to config.
I also updated the `npm start` command in the readme; there was some old information in there.
Run the site locally and ensure that the following code block appears in the source:
```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-107719124-1', 'auto');
ga('send', 'pageview');
</script>
```
No GitHub issue exists, but we discussed this feature in chat.
-----
-----
**Please note: we may close your PR without comment …

Add Google Analytics

---

site/content/about/brand.adoc
site/themes/uncontained.io/src/scss/_content.scss

setting text color for admonitions to white.
```
npm install
npm start
```
Look at http://localhost:3000/about/brand/ to see some sample admonitions
#84 
-----
-----

Fixing text color in admonitions

---

migrate-doc.sh
site/content/articles/openshift-template-infra-as-code.adoc
site/themes/uncontained.io/layouts/_default/list.html
site/themes/uncontained.io/layouts/index.html

Migrating and revamping the template guide for the new site.
Follow the instructions to [run the site preview](https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.md#building-and-developing-the-site), then:
- Read through the template guide content
- check that the article summaries look correct on the homepage, and articles pages
- Check the front matter
n/a
-----
-----

Migrating template guide; updating layouts to accomodate new articles

---

README.md

Now that we're soft-launched, it seems like a good time to add folks who were missing from the initial readme. Abby and Laura were instrumental in taking uncontained.io from a Hugo skeleton and a dream to a thoughtfully designed, trustworthy website.
Open the readme and make sure nothing looks amiss.
There isn't.
-----
-----

Add additional team members to acknowledgements

---

CONTRIBUTING.md
docs/content_model.md
docs/new_articles.md

Trying to make the contribution guide more comprehensive.
Read the changed docs, and provide feedback.
n/a
-----
-----

Updating contribution guide.

---

site/content/articles/openshift-monitoring-guide.adoc

Update monitoring guide for OCP 3.1x. Probably need to discuss if these commands should be considered "best practice." Putting something out there to start a conversation.
Run the new commands on any 3.1x cluster.
Issue #108
-----
- [ x] Have you followed the [contributing guidelines](https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.md)?
- [ x] Have you explained what your changes do, and why they add value to the uncontained.io guides?
-----

Update monitoring guide for OCP 3.1x, add additional escape chars

---

site/content/articles/openshift-ha-installation.adoc

==== What is this PR About?
Brief explanation of the guide or document changes you have made and/or
the new content you are contributing.
==== How should we test or review this PR?
Include any information or commands (please use code blocks) to help
reviewers understand and verify your contribution.
==== Is there a relevant Trello card or Github issue open for this?
Provide a link to any open Github issues or Trello cards that describe
the use case or problem you are solving.
==== Who would you like to review this?
'''''
* [ x ] Have you followed the
guidelines]?
* [ x ] Have you explained what your changes do, and why they add value to
''''' …

Updated Netscaler monitors 

---

.applier-prod/group_vars/seed-hosts.yml
.openshift/templates/promoter-sa.yml

==== What is this PR About?
See issue below
==== How should we test or review this PR?
```
ansible-playbook -i .applier/ galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml  -e source_repo=https://github.com/etsauer/uncontained.io.git -e source_ref=address-permission-issue
```
==== Is there a relevant Trello card or Github issue open for this?
#122 
==== Who would you like to review this?
'''''
guidelines]?
'''''

Put role binding back in place

---

site/content/articles/openshift-ha-installation.adoc

section of the document to take out the number based list and convert to a bullet space list for the kube args
==== What is this PR About?
fixed build issue with the site do to an ordered list not referencing the list.  I have since changed that to just an unordered list
Brief explanation of the guide or document changes you have made and/or
the new content you are contributing.
==== How should we test or review this PR?
Include any information or commands (please use code blocks) to help
reviewers understand and verify your contribution.
==== Is there a relevant Trello card or Github issue open for this?
Provide a link to any open Github issues or Trello cards that describe
the use case or problem you are solving.
==== Who would you like to review this? …

adjusted the openshift-ha-installation.adoc 

---

.gitignore
CONTRIBUTING.adoc
container-images/local-dev/Dockerfile
container-images/local-dev/README.adoc
container-images/local-dev/root/usr/local/bin/entrypoint
container-images/local-dev/root/usr/local/bin/user_setup

==== What is this PR About?
Adding a new container image to help with local dev. Instructions are in the contributing guide.
==== How should we test or review this PR?
```
git remote add etsauer https://github.com/etsauer/uncontained.io
git fetch etsauer
git checkout etsauer/improve-local-dev
docker build -f container-images/local-dev/Dockerfile -t uncontained-local-dev .
docker run -u $(id -u) --net=host -v $HOME/uncontained.io:/uncontained.io:Z -it uncontained-local-dev
```
Then, follow local dev instructions in the [contributing guide](https://github.com/etsauer/uncontained.io/blob/improve-local-dev/CONTRIBUTING.adoc#getting-set-up-for-local-development).
==== Is there a relevant Trello card or Github issue open for this?
n/a
==== Who would you like to review this?
cc: …

Improve local dev

---

CONTRIBUTING.adoc
container-images/local-dev/Dockerfile
container-images/local-dev/README.adoc
container-images/local-dev/root/usr/local/bin/user_setup

Fixing permissions issue when you run the container image.
Test all `docker run` commands in CONTRIBUTING.md
Also addresses #138 
'''''
guidelines]?
'''''

Fixing permissions issue with local-dev image

---

CONTRIBUTING.adoc

Refactors some of the contribution guide to make it easier to follow.
Read through CONTRIBUTING.md, evaluate the content flow, make sure links work, etc.
#137 
'''''
guidelines]?
'''''

Fix 137 and some other improvements

---

site/content/articles/openshift-ha-installation.adoc

Some updates to node provisioning storage guidance.
@sabre1041 @etsauer @JaredBurck 
'''''
guidelines]?
'''''

Some updates to node provisioning storage guidance

---

site/content/articles/openshift-ha-installation.adoc

Couple minor corrections to my most recent update.

Minor correction

---

site/content/articles/openshift-ha-installation.adoc

This PR fixes some inconsistencies I found while reading the Installing a Highly Available OpenShift Cluster article.
'''''
guidelines]?
* [ x] Have you explained what your changes do, and why they add value to
'''''

Openshift HA article fixes

---

CONTRIBUTING.adoc
site/content/articles/devops-reading-list.adoc
site/content/articles/external-jenkins-integration.adoc
site/content/articles/openshift-admin-overview.adoc
site/content/articles/openshift-ldap-integration.adoc
site/content/articles/openshift-monitoring-guide.adoc
site/content/articles/openshift-pre-install.adoc
site/content/articles/openshift-template-infra-as-code.adoc
site/content/articles/openshift-validate.adoc

Added DevOps Reading List and global search/replace correction for capitalization for OpenShift. Added fixes for Docker commands to run uncontained.io on Docker for MacOS.
Added DevOps Reading List and global search/replace correction for capitalization for OpenShift. Added fixes for Docker commands to run uncontained.io on Docker for MacOS.
Review as normal
Not that I know of
'''''
guidelines]?
* [X ] Have you explained what your changes do, and why they add value to
'''''

Added DevOps Reading List

---

site/content/articles/openshift-ha-installation.adoc

Just a few minor typo fixes to the ha-installation page.  Cleans up the document so that it's easier to present to customers.
Look at the diff and verify that I haven't mistakenly changed the context of the sentences by fixing the (suspected) typos.
Contribution guide said to just open a PR for quick typo fixes.
'''''
* [Y] Have you followed the
guidelines]?
* [Y] Have you explained what your changes do, and why they add value to
'''''

Fix spelling/typos only - no content changed

---

README.adoc

Add some badges to our readme to show that we are an active community.
See link:https://github.com/etsauer/uncontained.io/blob/readme-badges/README.adoc[the README]
n/a
'''''
guidelines]?
'''''

Readme badges

---

Gemfile

Bumped Asciidoctor to 2.x, per issue #145.
Run standard test suite.
resolves https://github.com/redhat-cop/uncontained.io/issues/145.
@etsauer, since he's the one that opened 145.

Bumped asciidoctor version to 2.0.10.

---

site/content/articles/openshift-and-the-org.adoc

Minor grammatical fixes to OpenShift and the Org article

Minor grammatical fixes to OpenShift and the Org

---

.github/PULL_REQUEST_TEMPLATE.md

Fixed link to contributing guide
Click on the link on master get a 404
'''''
guidelines]?
'''''

Fixed contributing link in gh template

---

site/themes/uncontained.io/src/scss/_content.scss
site/themes/uncontained.io/src/scss/_video.scss
site/themes/uncontained.io/src/scss/style.scss

Fix for issue #100.
Head to any page with a video (/articles/openshift-template-infra-as-code/ is one of them). Verify that the video expands to the full column width. Verify that the video width is responsive.
#100.
Probably @rdebeasi, since he originally opened the issue.

fix for #100

---

.openshift/files/builder-image.yml
Jenkinsfile
gulpfile.js

Use git29 package, which contains an appropriate version of git, instead of base git package for builds.
Run a build in Jenkins.
Related to #174   
cc: @etsauer 
'''''
[contributing
'''''

Use git29 package for Jenkins builds instead of git for -C.

---

.github/workflows/main.yml

Brief explanation of the guide or document changes you have made and/or
the new content you are contributing.
Include any information or commands (please use code blocks) to help
reviewers understand and verify your contribution.
Provide a link to any open Github issues or Trello cards that describe
the use case or problem you are solving.
'''''
[contributing
'''''

Add vale linting for natural language suggestions

---

site/content/articles/external-container-registry-integration.adoc

Removed extra `-n` from external registry integration document
Review change made
No

Removed extra -n in external registry integration

---

.dockerignore
.vale.ini
CONTRIBUTING.adoc
container-images/local-dev/Dockerfile
gulpfile.js
site/content/articles/devops-reading-list.adoc

Signed-off-by: Eric Sauer <esauer@redhat.com>
Refactoring container image to fix some build failures, and relax the ruby version requirements so we don't break as often.
See CI tests.
'''''
[contributing
'''''

Add a few changes to deal with image permissions and CI

---

gulpfile.js

This small PR addresses some user issues with builds not handling static files well.
Follow local dev guide, ensure that site builds and serves WITH css intact.
n/a
'''''
[contributing
'''''

Refactor gulpfil for more consistency between build and serve

---

site/content/articles/external-container-registry-integration.adoc
site/content/articles/openshift-validate.adoc

Basic edits to some content.
No testing needed
Nope. Just playing around and getting used to working in this doc set.
'''''
* [ X] Have you followed the
[contributing
* [ X] Have you explained what your changes do, and why they add value to
'''''

Basic edits
